### ISSUE TITLE
Featured exercice overflow

### ISSUE THREAD

**Issue by hannaeko** [AIR-EISTI/air-contest-spoutnik#1]
There is no max height on the description of the exercise thus it can lead to an ugly overflow.
![](https://i.imgur.com/KXJ6NKt.png)

Adding some height limit with eventually an overflow property can fix the problem.

```css
.month-exercise {
  height: 200px;
  overflow: auto;
}
```
